name: Claude Code Action Review
on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

jobs:
  cca-review:
    runs-on: ubuntu-latest
    # Skip for forked PRs - external contributors don't have access to repository secrets
    # This prevents the job from failing when secrets.ANTHROPIC_API_KEY is unavailable
    if: github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    environment:
      name: integration
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          track_progress: true
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            Please review this pull request with a focus on:
            - Code quality and best practices
            - Potential bugs or issues
            - Security implications
            - Performance considerations

            Please take @.ai/project-prd, @.ai/tech-stack and other applicable context documents into account.

            Provide detailed feedback using inline comments for specific issues.

          claude_args: |
            --allowedTools "mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*)"
