name: PR Dev Deployment

on:
  pull_request_target:
    branches: [master]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=ai-rules-builder --branch=${{ github.head_ref }}

      - name: Extract deployment URL
        run: |
          URL="https://${{ github.head_ref }}.ai-rules-builder.pages.dev"
          echo "🚀 Preview deployment is ready at $URL" >> $GITHUB_STEP_SUMMARY
